import { Router } from "express";
import { adminRouter } from "./admin.routes";
import { assistantRouter } from "./assistant.routes";
import { authRouter } from "./auth.routes";
import { bidsRouter } from "./bids.routes";
import { buildRouter } from "./build.routes";
import { callsRouter } from "./calls.routes";
import { contractsRouter } from "./contracts.routes";
import { disputesRouter } from "./disputes.routes";
import { geoRouter } from "./geo.routes";
import { marketplaceRouter } from "./marketplace.routes";
import { healthRouter } from "./health.routes";
import { keysRouter } from "./keys.routes";
import { meetingsRouter } from "./meetings.routes";
import { messagesRouter } from "./messages.routes";
import { nidRouter } from "./nid.routes";
import { notificationsRouter } from "./notifications.routes";
import { paymentsRouter } from "./payments.routes";
import { permitApplicationsRouter } from "./permitApplications.routes";
import { permitsRouter } from "./permits.routes";
import { pricingRouter } from "./pricing.routes";
import { professionalsRouter } from "./professionals.routes";
import { projectsRouter } from "./projects.routes";
import { publicRouter } from "./public.routes";
import { pushRouter } from "./push.routes";
import { proposalsRouter } from "./proposals.routes";
import { structuralRouter } from "./structural.routes";
import { tendersRouter } from "./tenders.routes";
import { inquiriesRouter } from "./inquiries.routes";
import { uploadsRouter } from "./uploads.routes";
import { verificationRouter } from "./verification.routes";

export const apiRouter = Router();

apiRouter.use("/health", healthRouter);
apiRouter.use("/auth", authRouter);
// Key management — ADMIN only.
apiRouter.use("/keys", keysRouter);
apiRouter.use("/professionals", professionalsRouter);
apiRouter.use("/inquiries", inquiriesRouter);
apiRouter.use("/uploads", uploadsRouter);
apiRouter.use("/verification", verificationRouter);
apiRouter.use("/nid", nidRouter);
apiRouter.use("/projects", projectsRouter);
apiRouter.use("/proposals", proposalsRouter);
apiRouter.use("/contracts", contractsRouter);
apiRouter.use("/structural", structuralRouter);
apiRouter.use("/tenders", tendersRouter);
apiRouter.use("/bids", bidsRouter);
apiRouter.use("/build", buildRouter);
apiRouter.use("/payments", paymentsRouter);
apiRouter.use("/messages", messagesRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/push", pushRouter);
apiRouter.use("/disputes", disputesRouter);
apiRouter.use("/public", publicRouter);
apiRouter.use("/calls", callsRouter);
apiRouter.use("/meetings", meetingsRouter);
apiRouter.use("/permits", permitsRouter);
apiRouter.use("/permit-applications", permitApplicationsRouter);
apiRouter.use("/pricing", pricingRouter);
apiRouter.use("/geo", geoRouter);
apiRouter.use("/assistant", assistantRouter);
apiRouter.use("/marketplace", marketplaceRouter);
apiRouter.use("/admin", adminRouter);
