import { Router } from "express";
import { adminRouter } from "./admin.routes";
import { assistantRouter } from "./assistant.routes";
import { authRouter } from "./auth.routes";
import { contractsRouter } from "./contracts.routes";
import { marketplaceRouter } from "./marketplace.routes";
import { healthRouter } from "./health.routes";
import { messagesRouter } from "./messages.routes";
import { permitsRouter } from "./permits.routes";
import { professionalsRouter } from "./professionals.routes";
import { projectsRouter } from "./projects.routes";
import { proposalsRouter } from "./proposals.routes";
import { inquiriesRouter } from "./inquiries.routes";
import { uploadsRouter } from "./uploads.routes";
import { verificationRouter } from "./verification.routes";

export const apiRouter = Router();

apiRouter.use("/health", healthRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/professionals", professionalsRouter);
apiRouter.use("/inquiries", inquiriesRouter);
apiRouter.use("/uploads", uploadsRouter);
apiRouter.use("/verification", verificationRouter);
apiRouter.use("/projects", projectsRouter);
apiRouter.use("/proposals", proposalsRouter);
apiRouter.use("/contracts", contractsRouter);
apiRouter.use("/messages", messagesRouter);
apiRouter.use("/permits", permitsRouter);
apiRouter.use("/assistant", assistantRouter);
apiRouter.use("/marketplace", marketplaceRouter);
apiRouter.use("/admin", adminRouter);
